#!/bin/bash

find -exec touch \{\} \;

make

#perf stat -e L1-dcache-loads,L1-dcache-load-misses,L1-dcache-stores,L1-dcache-store-misses,L1-icache-loads,L1-icache-load-misses,cpu-clock,task-clock,bpf-output,dummy,page-faults,major-faults,minor-#faults,alignment-faults,emulation-faults,cpu-cycles,instructions,bus-cycles,cache-references,cache-misses,cpu-migrations,context-switches,branch-instructions,branch-misses,branch-loads,branch-load-#misses,dTLB-load-misses,dTLB-store-misses,iTLB-load-misses,LLC-loads,LLC-load-misses,LLC-stores,LLC-store-misses -o t2 ./sha runme_large.sh

perf stat -e cpu-cycles,instructions,bus-cycles,cache-references,cache-misses,branch-instructions,branch-misses -o t2 taskset -c 4,5,6,7 ./basicmath_large runme_large.sh
perf stat -e L1-dcache-loads,L1-dcache-load-misses,L1-dcache-stores,L1-dcache-store-misses,L1-icache-loads,L1-icache-load-misses -o tt taskset -c 4,5,6,7 ./basicmath_large runme_large.sh
perf stat -e dTLB-load-misses,iTLB-load-misses,LLC-loads,LLC-load-misses,LLC-stores,LLC-store-misses -o tz taskset -c 4,5,6,7 ./basicmath_large runme_large.sh
 
pid=$(pgrep telnet)
kill $pid
cat tt >> t2
cat tz >> t2
 
clang r.c -o r0
./r0 

awk -F, '{print $3}' power.txt > avgpower.xls


mkdir noc-4
mkdir opt-0

mv avgpower.xls ./opt-0
mv log.txt ./opt-0
mv t2 ./opt-0
mv opt-0 ./noc-4
mv noc-4 ./freq-2000
